# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: quantta
service: serverless-express-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev # Customize as dev, staging, prod
  timeout: 10 # Max Lambda duration in seconds
  memorySize: 256 # Adjust based on app needs

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

plugins:
  - serverless-dotenv-plugin # Load .env files into environment

package:
  exclude:
    - node_modules/aws-sdk # AWS SDK is already available in Lambda
    - .git/**
    - .vscode/**
    - test/**
    - README.md
    - server.js
    - .env
